# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'app/qtui/desing.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(376, 90)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.actions_horizontalLayout = QtWidgets.QHBoxLayout()
        self.actions_horizontalLayout.setObjectName("actions_horizontalLayout")
        self.plot_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.plot_pushButton.setCheckable(False)
        self.plot_pushButton.setAutoRepeat(False)
        self.plot_pushButton.setAutoExclusive(False)
        self.plot_pushButton.setObjectName("plot_pushButton")
        self.actions_horizontalLayout.addWidget(self.plot_pushButton)
        self.open_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.open_pushButton.setFlat(False)
        self.open_pushButton.setObjectName("open_pushButton")
        self.actions_horizontalLayout.addWidget(self.open_pushButton)
        self.update_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.update_pushButton.setObjectName("update_pushButton")
        self.actions_horizontalLayout.addWidget(self.update_pushButton)
        self.verticalLayout.addLayout(self.actions_horizontalLayout)
        self.exit_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.exit_pushButton.setEnabled(True)
        self.exit_pushButton.setAutoDefault(False)
        self.exit_pushButton.setDefault(False)
        self.exit_pushButton.setObjectName("exit_pushButton")
        self.verticalLayout.addWidget(self.exit_pushButton)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.plot_pushButton.setText(_translate("MainWindow", "Plot graph"))
        self.open_pushButton.setText(_translate("MainWindow", "Open file"))
        self.update_pushButton.setText(_translate("MainWindow", "Update database"))
        self.exit_pushButton.setText(_translate("MainWindow", "Exit"))
